language: rust

rust:
  - stable
  - beta

sudo: false

cache: cargo

before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test
